/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_almasb_fxgl_controllerinput_NativeController */

#ifndef _Included_com_almasb_fxgl_controllerinput_NativeController
#define _Included_com_almasb_fxgl_controllerinput_NativeController
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     com_almasb_fxgl_controllerinput_NativeController
     * Method:    connect
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_com_almasb_fxgl_controllerinput_NativeController_connect
    (JNIEnv*, jobject);

    /*
     * Class:     com_almasb_fxgl_controllerinput_NativeController
     * Method:    disconnect
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_com_almasb_fxgl_controllerinput_NativeController_disconnect
    (JNIEnv*, jobject);

    /*
     * Class:     com_almasb_fxgl_controllerinput_NativeController
     * Method:    isButtonPressed
     * Signature: (I)Z
     */
    JNIEXPORT jboolean JNICALL Java_com_almasb_fxgl_controllerinput_NativeController_isButtonPressed
    (JNIEnv*, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
