/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_almasb_fxgl_controllerinput_impl_GameControllerImpl */

#ifndef _Included_com_almasb_fxgl_controllerinput_impl_GameControllerImpl
#define _Included_com_almasb_fxgl_controllerinput_impl_GameControllerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_almasb_fxgl_controllerinput_impl_GameControllerImpl
 * Method:    getBackendVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_almasb_fxgl_controllerinput_impl_GameControllerImpl_getBackendVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_almasb_fxgl_controllerinput_impl_GameControllerImpl
 * Method:    connectControllers
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_almasb_fxgl_controllerinput_impl_GameControllerImpl_connectControllers
  (JNIEnv *, jclass);

/*
 * Class:     com_almasb_fxgl_controllerinput_impl_GameControllerImpl
 * Method:    updateState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_almasb_fxgl_controllerinput_impl_GameControllerImpl_updateState
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_almasb_fxgl_controllerinput_impl_GameControllerImpl
 * Method:    isButtonPressed
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_almasb_fxgl_controllerinput_impl_GameControllerImpl_isButtonPressed
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_almasb_fxgl_controllerinput_impl_GameControllerImpl
 * Method:    getAxis
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_com_almasb_fxgl_controllerinput_impl_GameControllerImpl_getAxis
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_almasb_fxgl_controllerinput_impl_GameControllerImpl
 * Method:    disconnectControllers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_almasb_fxgl_controllerinput_impl_GameControllerImpl_disconnectControllers
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
