name: Deploy dev-SNAPSHOT

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Cache maven deps
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build and test with Maven using xvfb
      uses: GabrielBB/xvfb-action@v1
      with:
        run: |
          mvn test -B -Dmaven.javadoc.skip=true -Djacoco.skip=true

    - name: Deploy SNAPSHOT build
      run: mvn deploy -DskipTests=true -Dlicense.skip=true -Dpmd.skip=true
      env:
        MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        MAVEN_GPG_PASSPHRASE : ${{ secrets.GPG_PASSPHRASE }}